In [1]:
import utils.DataManager
dataManager = utils.DataManager.DataManager("E:\TFG\core_dataset", "lr_dataset", "hr_dataset/12bit")
print(dataManager.data_points)
hr, lr = dataManager.get_random_data(10)

            points_name
0     ASMSpotter-28-2-1
1      UNHCR-NGAs037523
2      Landcover-777479
3            UNHCR-3645
4      ASMSpotter-3-1-3
...                 ...
3924   Landcover-145671
3925   Landcover-769563
3926  Landcover-1736070
3927   Landcover-394716
3928  Amnesty POI-2-2-1

[3929 rows x 1 columns]


FileNotFoundError: [Errno 2] No such file or directory: 'E:\\TFG\\core_dataset\\lr_dataset\\UNHCR-IRQs003273\\L2A\\UNHCR-IRQs003273-3-L2ACLM.tiff'

In [2]:
for i in lr:
    print(i.shape)

(159, 157, 12)
(158, 158, 12)
(159, 157, 12)
(159, 158, 12)
(160, 156, 12)
(156, 160, 12)
(158, 159, 12)
(159, 158, 12)
(159, 157, 12)
(157, 159, 12)


In [33]:
import tifffile
image = tifffile.imread("E:\TFG\core_dataset\lr_dataset\Amnesty POI-1-1-1\L2A\Amnesty POI-1-1-1-2-L2A_data.tiff")
print(type(image))
print(image)

<class 'numpy.ndarray'>
[[[0.0822 0.1064 0.1394 ... 0.2203 0.2421 0.2301]
  [0.0822 0.0888 0.1188 ... 0.2203 0.2421 0.2301]
  [0.0904 0.1048 0.1384 ... 0.229  0.2439 0.2172]
  ...
  [0.0569 0.0721 0.1282 ... 0.347  0.4256 0.3324]
  [0.0569 0.0689 0.122  ... 0.347  0.404  0.3054]
  [0.0569 0.0717 0.1262 ... 0.347  0.404  0.3054]]

 [[0.0822 0.0872 0.1248 ... 0.2203 0.2421 0.2301]
  [0.0822 0.0966 0.1288 ... 0.2203 0.2421 0.2301]
  [0.0904 0.124  0.145  ... 0.229  0.2439 0.2172]
  ...
  [0.0569 0.0891 0.152  ... 0.347  0.4274 0.3389]
  [0.0569 0.0781 0.1416 ... 0.347  0.411  0.3218]
  [0.0569 0.0812 0.1424 ... 0.347  0.411  0.3218]]

 [[0.0822 0.0888 0.1136 ... 0.2203 0.261  0.2439]
  [0.0822 0.0984 0.1306 ... 0.2203 0.261  0.2439]
  [0.0904 0.1172 0.1482 ... 0.229  0.2553 0.243 ]
  ...
  [0.0569 0.0852 0.1454 ... 0.347  0.4274 0.3389]
  [0.0569 0.0852 0.1376 ... 0.347  0.411  0.3218]
  [0.0569 0.0938 0.1578 ... 0.347  0.411  0.3218]]

 ...

 [[0.0563 0.1224 0.1784 ... 0.3189 0.4462 0.33

In [34]:
test = image[:,:,6:9]
print(test.shape)

(157, 159, 3)


In [35]:
tifffile.imsave("E:\\test.tiff", test)

In [3]:
#Otra forma de leer bien los datos satelitales
import osgeo.gdal as gdal
import numpy as np
import matplotlib.pyplot as plt

directory = "E:\TFG\core_dataset\lr_dataset\Amnesty POI-1-1-1\L2A\Amnesty POI-1-1-1-2-"

# Lista de nombres de archivos de entrada
file_names = [
    directory + "CLM.tiff",
    directory + "CLP.tiff",
    directory + "L2A_data.tiff",
    directory + "dataMask.tiff",
    directory + "sunAzimuthAngles.tiff",
    directory + "sunZenithAngles.tiff",
    directory + "viewAzimuthMean.tiff",
    directory + "viewZenithMean.tiff"
]

# Crear una lista para almacenar los datos de cada archivo
data_list = []

# Leer los datos de cada archivo TIFF y almacenarlos en la lista
for file_name in file_names:
    dataset = gdal.Open(file_name)
    if dataset is None:
        print(f"No se pudo abrir el archivo {file_name}")
    else:
        data = dataset.ReadAsArray()
        data_list.append(data)

# Combinar los datos en una imagen
combined_image = np.stack(data_list, axis=-1)

# Normalizar los valores para la visualización
combined_image = combined_image.astype(np.float32)
combined_image -= combined_image.min()
combined_image /= combined_image.max()

# Mostrar la imagen combinada
plt.imshow(combined_image)
plt.axis('off')
plt.show()

ImportError: Traceback (most recent call last):
  File "C:\Users\adria\miniconda3\envs\cuda\Lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adria\miniconda3\envs\cuda\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: No se puede encontrar el módulo especificado.

On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
to feed the PATH into os.add_dll_directory().